# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
warnings_are_errors: true

r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --as-cran"
